### ISSUE TITLE
Do not modify text data

### ISSUE THREAD

**Issue by kat-kel** [medialab/spsm-database#3]
Currently, in order to avoid an error, we modify all text data by replacing every single quote `'` with 2 single quotes `''`. We should not be modifying / cleaning the data at this stage.

One idea:
Add an escape character before the single quote when inserting into the table.
Replace the last line of this:
https://github.com/medialab/spsm-database/blob/55ae14b7542cf39842e3a90428c72ef2ded9ec6f/src/build-database/tables/base_classes.py#L151-L156
With this:
```
values.append(f"'{value.replace("'", "\'")}'")
```

Another idea:
Look into Python PostgreSQL ORM to construct the query and properly handle text data.

**Comment by kat-kel** [comment]
Here's an example of a query that produces an error. The error is caused by a single quote, which is not escaped in text that is being inserted into a table:

SQL query:
```
INSERT INTO twitter_user(screen_name, id, display_name, description, image, tweets, followers, friends, lists, created_at, collection_time) VALUES ('AnnStew80895938', '715046844', 'Ann Stewart', 'Attended KCVI, Queen's. 
Reading/Politics/History/Ancestry/hockey
"There are more things in heaven & earth Horatio than are dreamt of in your philosophy".', 'https://pbs.twimg.com/profile_images/524974597964193793/T7ov8v62_normal.jpeg', '176027', '1442', '490', '12', '2012-07-24T22:40:49', '2023-03-19T13:41:30.204498')
```

error:
```
psycopg2.errors.SyntaxError: syntax error at or near "s"
LINE 2: ...5938', '715046844', 'Ann Stewart', 'Attended KCVI, Queen's. 
```

**Comment by boogheta** [comment]
Try in the postgresl cli to run fixed version of the same query by escaping the quote with an antislash probably, if that works then you should build your queries that way

**Comment by Yomguithereal** [comment]
Shouldn’t you use query parameters there though?

**Comment by kat-kel** [comment]
Is this the sort of thing that you're talking about, Guillaume?

https://stackoverflow.com/questions/44689359/insert-row-into-psql-db-using-psycopg2

"You should never use string formatting for placing values into sql query. Instead, you should use %s and pass the name in the vars parameter. The reason behind doing it this way is because it helps you convert the parameters into the appropriate data types.

"Btw, having a ; at the end in the sql string is redundant when called by cursor.execute, since it does it for you automatically.

```
c.execute("INSERT INTO players(player_name) VALUES(%(name)s)", {"name":name})
```

**Comment by kat-kel** [comment]
There's some good documentation here, which makes me think I should switch to v3.

https://www.psycopg.org/psycopg3/docs/basic/params.html

**Comment by Yomguithereal** [comment]
> Is this the sort of thing that you're talking about, Guillaume?

Yup. It's dangerous to interpolate query params in the string oneself and can lead to corrupt queries, and what's more problematic, SQL injection attacks, even if this is not a concern here.

Also most SQL DBMS are able to leverage parametrization for caching purposes.
